#
# Build the image
#   docker build -t ottwatch-dev -f Dockerfile.dev .
#
# Run the container and load the current directory at /ottwatch
#   docker run --name ottwatch-dev -v `pwd`:/ottwatch -i -t ottwatch-dev
#   docker start -i ottwatch-dev
#
FROM ottwatch-base
USER app

# Then run the image (create a container), via: 
# docker run --rm -v `pwd`:/app -p 33000:3000 -i -t --name ottwatch-dev ottwatch-dev
# docker run --rm -v `pwd`:/app -i -t --name ottwatch-dev ottwatch-dev
# docker run --rm -v `pwd`:/app -i -t ottwatch-dev

