#
# Build the image
#   docker build -t ottwatch-dev -f Dockerfile.dev .
#
# Run the container and load the current directory at /ottwatch
#   docker run --name ottwatch-dev -p 33000:3000 -v `pwd`:/ottwatch -i -t ottwatch-dev
#   docker start -i ottwatch-dev
#
FROM ottwatch-base

USER app


# bundle config set --local path 'vendor/bundle'
# bundle install
