#
# Build the image
#   docker build -t ottwatch-prod -f Dockerfile.prod .
#
FROM ottwatch-base

RUN mkdir /app && chown app:app /app

WORKDIR /app
USER app

RUN git clone https://github.com/kevinodotnet/ottwatch.git

WORKDIR /app/ottwatch
RUN ls -lF
RUN pwd
RUN bundle config set --local path 'vendor/bundle'`
RUN bundle install
