#
# Build the image
#   sudo docker build -t ottwatch-prod -f Dockerfile.prod .
#
FROM ottwatch-base

# only once per commit to main
RUN git checkout . && git clean -df .
ADD --chown=app:app https://api.github.com/repos/kevinodotnet/ottwatch/git/refs/heads/main /tmp/version.json
ADD --chown=app:app https://api.github.com/repos/kevinodotnet/ottwatch/git/refs/heads/main version.json
RUN git pull
RUN bundle install
RUN bin/rails assets:precompile
ENV RAILS_LOG_TO_STDOUT=true
