production:
  dev_app_scan_job:
    class: DevAppScanJob
    schedule: "30 */3 * * *"
  lobbying_scan_job:
    class: LobbyingScanJob
    schedule: "45 */3 * * *"
  meeting_scan_job:
    class: MeetingScanJob
    schedule: "0 */3 * * *"
  parcel_scanner:
    class: ParcelScanner
    schedule: "0 2 1,2,3 * *"
  zoning_scanner:
    class: ZoningScanner
    schedule: "0 2 1,2,3 * *"
  consultation_scanner:
    class: ConsultationScanner
    schedule: "10 */3 * * *"
  traffic_camera_scrape_job:
    class: TrafficCameraScrapeJob
    schedule: "*/5 * * * *"
  syndication_job:
    class: SyndicationJob
    schedule: "* * * * *"
  gtfs_download_job:
    class: GtfsDownloadJob
    schedule: "0 5 * * *"
  gtfs_rt_download_job:
    class: GtfsRtDownloadJob
    schedule: "*/3 * * * *"
  gtfs_rt_trip_updates_job:
    class: GtfsRtTripUpdatesJob
    schedule: "*/3 * * * *"
