# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12)
# │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
# │ │ │ │ │                                   7 is also Sunday on some systems)
# │ │ │ │ │
# │ │ │ │ │
# * * * * * <command to execute>

dev_app_scan_job:
   cron: "30 10-20 * * *"
   class: "DevAppScanJob"

lobbying_scan_job:
   cron: "45 10-20 * * *"
   class: "LobbyingScanJob"

meeting_scan_job:
   cron: "0 10-20 * * *"
   class: "MeetingScanJob"

election_scan_job:
   cron: "10,30,50 * * * *"
   class: "ElectionScanJob"

syndication_job:
   cron: "* * * * *"
   class: "SyndicationJob"
