# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12)
# │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
# │ │ │ │ │                                   7 is also Sunday on some systems)
# │ │ │ │ │
# │ │ │ │ │
# * * * * * <command to execute>

dev_app_scan_job:
   cron: "30 10-20 * * *"
   class: "DevAppScanJob"

lobbying_scan_job:
   cron: "45 10-20 * * *"
   class: "LobbyingScanJob"

meeting_scan_job:
   cron: "0 6,10,14,16,20 * * *"
   class: "MeetingScanJob"

parcel_scanner:
   cron: "0 2 1,2,3 * *"
   class: "ParcelScanner"

zoning_scanner:
   cron: "0 2 1,2,3 * *"
   class: "ZoningScanner"

consultation_scanner:
   cron: "10 10-20 * * *"
   class: "ConsultationScanner"

# service_request_scan_job:
#    cron: "*/10 * * * *"
#    class: "ServiceRequestScanJob"

# syndication_job:
#    cron: "* * * * *"
#    class: "SyndicationJob"
